(SIMP-9654) - 389-DS Account Management
simp/pupmod-simp-ds389 pull request #3
Opened 2021-05-04 12:59 UTC by trevor-vaughan

Updated the default instance LDIF template:
  * Allow for account creation
  * Allow for management of accounts with the dsidm system
  * Add the default global password policy
  * Add a custom password policy for 'Host' entries like 'hostAuth'

SIMP-9656 #close
SIMP-9657 #close

2021-05-04 18:08 UTC, lnemsick-simp commented on spec/acceptance/suites/default/50_sssd_spec.rb
> +        'simp_options::clamav'          => true,
Don't think simp_options::clamav is a thing anymore

2021-05-04 18:10 UTC, lnemsick-simp commented on spec/acceptance/suites/default/50_sssd_spec.rb
> +        'simp_options::selinux'         => true,
simp_options::selinux no longer exists

2021-05-05 14:00 UTC, trevor-vaughan commented
The modifications to the GitHub Actions [allow this to pass](https://github.com/trevor-vaughan/pupmod-simp-ds389/actions/runs/810827605), but the changes won't be picked up until after this PR has been merged.

2021-05-07 13:26 UTC, jeannegreulich commented on spec/acceptance/suites/default/50_sssd_spec.rb
> +          skip(dsidm_skip_message)
The metadata.json has EL7 being the only OS supported but you  are skipping testing el7.  SHould the metadata.json be updated?

2021-05-07 17:35 UTC, jeannegreulich reviewed
I can't change the password of my user using passwd/  Am I supposed to be able to do this  after sssd is set up?

2021-05-07 21:34 UTC, jeannegreulich requested changes
You have the default for $source in instance/tls.pp set incorrectly.  It should be undef to get pki::copys default or /etc/pki/simp/x509.
THe default you have causes an error because it is a relative patch.

2021-05-10 20:34 UTC, jeannegreulich approved these changes

2021-05-10 20:35 UTC, merged